// WayPAY — Danish translations + English key facts for all premium explainer keys
// Loaded before premium-page.js so it can merge before rendering.

window.WAYPAY_EN_FACTS = {
  barber:        ['Customers book without calling','Prepayment reduces no-shows','Automatic reminder sent before the appointment'],
  beauty:        ['Treatments sold with clear price and duration','Packages and add-ons increase average order value','Automatic confirmation builds customer confidence'],
  nails:         ['Repeat clients re-book with one click','Designs and add-ons shown clearly in the flow','Reminders cut down no-shows for nail appointments'],
  physio:        ['Treatment plans managed automatically','Patients get reminders before every visit','Fewer cancelled sessions with clear agreements'],
  therapy:       ['Clients book discreetly and privately','Cancellation rules shown clearly at booking','Confidentiality supported throughout the flow'],
  yoga:          ['Class capacity updated automatically','Passes and packages sold in the same flow','Waitlist reduces empty spots in small classes'],
  consultant:    ['Clients book the session before the first email','Packages and single sessions sold clearly','Payment at booking — no invoice needed'],
  education:     ['Capacity updates automatically on signup','Payment at signup ensures commitment','Participants receive clear confirmation'],
  cleaning:      ['Service agreements run automatically after setup','Customers choose frequency and payment plan','No manual invoicing per visit'],
  garden:        ['Seasonal service easy to plan online','Customers choose task and visit window themselves','Recurring agreements run automatically'],
  roof:          ['Customers request inspection online','Visit windows chosen by the customer','Follow-up and quote linked to the first request'],
  auto:          ['Customers enter vehicle details at booking','Drop-off windows shown clearly','Workshop receives the order ready before arrival'],
  equipment:     ['Availability shown in real time','Deposit and return terms clear at booking','Late returns handled automatically'],
  pet:           ['Customers see service details clearly before booking','Repeat visits can be scheduled automatically','Reminders ensure consistent attendance'],
  photography:   ['Deposit secures commitment before the shoot','Packages and add-ons clearly sold in the flow','Client expectations clarified before the day'],
  onlineBooking: ['Customers see available times without calling','Booking confirmed automatically','Business receives the order ready to act on'],
  prepayment:    ['A paid booking is harder to forget','Prepayment improves cashflow from day one','Receipt sent automatically at booking'],
  reminders:     ['Confirmation sent automatically at booking','Reminder sent before every visit','Customers remember better — fewer support messages'],
  bookingWebsite:['Page explains service value before booking','CTA and booking on the same page','SEO and AEO structure built in'],
  rentalDeposit: ['Deposit and return terms shown before booking','Customer accepts terms online','Damage fees and return clearly defined'],
  subscriptions: ['Customer picks plan — payment runs automatically','Failed payments handled automatically','Customer portal gives self-service'],
};

window.WAYPAY_DA = {
  barber: {
    headline: 'Hurtig booking til barberstolen.',
    subline: 'Kunder vælger service, barber og tid uden at afbryde arbejdsdagen.',
    pills: ['Lynbooking','Vælg barber','No-show beskyttelse'],
    metrics: [{value:'30',label:'min pr. klip'},{value:'↓40%',label:'no-shows'},{value:'24/7',label:'online booking'}],
    keyFacts: ['Kunder booker uden at ringe','Forudbetaling reducerer no-shows','Automatisk påminding sendes inden aftalen'],
    problemBadge: 'Barber-problemet',
    problemTitle: 'Et kort no-show kan ødelægge den daglige rytme.',
    problemText: 'Barbere har brug for hurtig, pålidelig booking med færre beskeder og tydeligt commitment fra kunden.',
    photoTitle: 'Barber shop rytme',
    photoText: 'Et premium barber-flow bygget til korte aftaler og stabilt fremmøde.',
    uiKicker: 'WayPAY Barber',
    uiTitle: 'Fade cut · 30 min',
    uiRows: [{title:'Barber',text:'Vælg foretrukken barber'},{title:'Tid',text:'I dag 15:00'}],
    uiButton: 'Book og betal',
    solutionBadge: 'Kundeflow',
    solutionTitle: 'Kunden booker stolen, inden de skriver en besked.',
    solutionText: 'Service, barber, tid og betaling håndteres i ét flow.',
    flowBadge: 'Barber-flow',
    flowTitle: 'Fra ledig tid til bekræftet aftale',
    flow: [{title:'Vælg service',text:'Fade, klip eller skæg — kunden vælger selv.'},{title:'Vælg barber',text:'Vælg foretrukken barber eller første ledige.'},{title:'Vælg tid',text:'Kun ledige tider vises.'},{title:'Betal og lås',text:'Forudbetaling sikrer stolen.'}],
    featuresBadge: 'Barber-features',
    featuresTitle: 'Bygget til hurtige aftaler.',
    featuresText: 'Explaineren fokuserer på korte services, stammekunder og reduktion af no-shows.',
    features: [{icon:'fa-scissors',title:'Lynbooking',text:'Klaret på under 60 sekunder.'},{icon:'fa-user',title:'Barbervalg',text:'Kunden vælger sin foretrukne.'},{icon:'fa-credit-card',title:'Forudbetaling',text:'Reducerer no-shows markant.'},{icon:'fa-bell',title:'Påminding',text:'Automatisk reminder inden klippet.'}],
    ctaTitle: 'Hold stolen booket',
    ctaText: 'Gør barber-booking hurtig, klar og betalt.',
    voiceovers: ['Barber-booking kræver hastighed og pålidelighed.','Et kort no-show kan forstyrre hele dagen.','Kunden vælger barber, service og tid.','Flowet er service, barber, tid og betaling.','Dette er skræddersyet til barbershops.','Hold stolen booket.'],
  },
  beauty: {
    headline: 'Sælg behandlinger, pakker og tilvalg online.',
    subline: 'Beauty-kunder kan vælge behandlingstype, pakke, tilvalg og betale i ét flow.',
    pills: ['Behandlinger','Pakker','Tilvalg'],
    metrics: [{value:'5+',label:'behandlingstyper'},{value:'↑35%',label:'tilvalgs-omsætning'},{value:'0',label:'dobbeltbookinger'}],
    keyFacts: ['Behandlinger sælges med klar pris og varighed','Pakker og tilvalg øger den gennemsnitlige ordreværdi','Automatisk bekræftelse giver kunden tryghed'],
    problemBadge: 'Beauty-problemet',
    problemTitle: 'Behandlinger kræver klarhed, inden kunden booker.',
    problemText: 'Forskellige services, varigheder og tilvalg kan forvirre kunder, hvis flowet ikke er klart.',
    photoTitle: 'Beauty behandlingsrejse',
    photoText: 'Et visuelt flow fokuseret på behandlinger, pakker og premium kundeoplevelse.',
    uiKicker: 'WayPAY Beauty',
    uiTitle: 'Ansigtsbehandling',
    uiRows: [{title:'Pakke',text:'Enkelt eller 5-sessioners plan'},{title:'Tilvalg',text:'Opgradering ved betaling'}],
    uiButton: 'Book behandling',
    solutionBadge: 'Beauty-flow',
    solutionTitle: 'WayPAY gør servicevalget til en klar betaling.',
    solutionText: 'Kunder forstår behandlingen, vælger tilvalg og bekræfter online.',
    flowBadge: 'Behandlingsflow',
    flowTitle: 'Fra interesse til betalt behandling',
    flow: [{title:'Vælg behandling',text:'Ansigt, vipper eller krop — klare valgmuligheder.'},{title:'Vælg pakke',text:'Enkelt session eller multi-sessioners plan.'},{title:'Tilføj tilvalg',text:'Tilvalg tilbydes inden betaling.'},{title:'Betal og bekræft',text:'Kunden modtager bekræftelse øjeblikkeligt.'}],
    featuresBadge: 'Beauty-features',
    featuresTitle: 'Bygget til behandlinger og pakker.',
    featuresText: 'Explaineren fremhæver tilvalg, behandlingspakker og forudbetaling.',
    features: [{icon:'fa-star',title:'Behandlingsmenu',text:'Alle services forklaret klart.'},{icon:'fa-gift',title:'Pakker',text:'Multi-sessioners planer reducerer churn.'},{icon:'fa-plus',title:'Tilvalg',text:'Opgrader ved betaling.'},{icon:'fa-credit-card',title:'Forudbetaling',text:'Sikrer commitment på forhånd.'}],
    ctaTitle: 'Gør beauty-booking nemmere',
    ctaText: 'Lad kunder booke og betale med tillid.',
    voiceovers: ['Beauty-booking kræver klare behandlingsvalg.','Pakker og tilvalg må ikke skabe forvirring.','WayPAY gør servicevalget visuelt og betalt.','Flowet er behandling, pakke, tilvalg og booking.','Dette er designet til beauty-saloner.','Gør beauty-booking nemmere.'],
  },
  nails: {
    headline: 'Gør negleaftaler til gentagne bookinger.',
    subline: 'Kunder vælger service, design-tilvalg og tidspunkt med klar betaling.',
    pills: ['Refills','Nail art','Gentagne besøg'],
    metrics: [{value:'60',label:'min gns. besøg'},{value:'↑60%',label:'gentagne bookinger'},{value:'24/7',label:'online booking'}],
    keyFacts: ['Stamkunder kan nemt genbooke','Design og tilvalg vises klart i flowet','Påmindelser reducerer udeblivelser'],
    problemBadge: 'Nail studio-problemet',
    problemTitle: 'Stamkunder har brug for enkel genbooking.',
    problemText: 'Negle-services gentager sig, men designvalg, tilvalg og varighed varierer.',
    photoTitle: 'Nail studio booking',
    photoText: 'En negle-specifik rejse med designs, refills, tilvalg og gentagne aftaler.',
    uiKicker: 'WayPAY Negle',
    uiTitle: 'Gel refill · 60 min',
    uiRows: [{title:'Design',text:'Fransk, farve eller nail art'},{title:'Genbooking',text:'Næste besøg foreslås'}],
    uiButton: 'Book negle',
    solutionBadge: 'Negle-flow',
    solutionTitle: 'WayPAY gør det nemt at acceptere næste aftale.',
    solutionText: 'Kunder vælger stil, tid og betaling uden frem-og-tilbage-beskeder.',
    flowBadge: 'Negle-flow',
    flowTitle: 'Fra designvalg til bekræftet aftale',
    flow: [{title:'Vælg service',text:'Gel, refill eller nail art — kunden vælger design.'},{title:'Vælg tid',text:'Ledige tider med korrekt varighed.'},{title:'Betal depositum',text:'Depositum låser aftalen.'},{title:'Påminding',text:'Automatisk reminder og genbookingsforslag.'}],
    featuresBadge: 'Nail studio-features',
    featuresTitle: 'Bygget til gentagne besøg.',
    featuresText: 'Explaineren fokuserer på refills, nail art, tilvalg og påmindelser.',
    features: [{icon:'fa-diamond',title:'Servicemenu',text:'Gel, refill og art — klart oplistet.'},{icon:'fa-repeat',title:'Genbooking',text:'Foreslå næste besøg ved bekræftelse.'},{icon:'fa-paint-brush',title:'Designvalg',text:'Kunden vælger stil på forhånd.'},{icon:'fa-bell',title:'Påminding',text:'Reducerer last-minute aflysninger.'}],
    ctaTitle: 'Fyld kalenderen med stamkunder',
    ctaText: 'Gør negle-aftaler nemme at genbooke.',
    voiceovers: ['Nail studios har brug for gentagne bookinger.','Design og tilvalg skal være klare.','WayPAY skaber et simpelt flow for stil, tid og betaling.','Flowet er service, design, tid og påminding.','Dette er skræddersyet til nail studios.','Fyld kalenderen med stamkunder.'],
  },
  physio: {
    headline: 'Strukturer sessioner og behandlingsforløb.',
    subline: 'Patienter booker sessioner, følger behandlingsplaner og modtager klare bekræftelser.',
    pills: ['Behandlingsforløb','Sessioner','Opfølgning'],
    metrics: [{value:'5',label:'sessions-planer'},{value:'↓30%',label:'aflysninger'},{value:'100%',label:'struktureret'}],
    keyFacts: ['Behandlingsforløb styres automatisk','Patienter får påmindelser inden hvert besøg','Færre aflyste sessioner med klar aftale'],
    problemBadge: 'Fysio-problemet',
    problemTitle: 'Behandlingsforløb kræver kontinuitet.',
    problemText: 'Flere sessioner, opfølgning og aflysninger bliver svære at styre manuelt.',
    photoTitle: 'Behandlingsplan booking',
    photoText: 'Et klinisk men venligt flow fokuseret på sessioner, opfølgning og struktur.',
    uiKicker: 'WayPAY Fysio',
    uiTitle: 'Opfølgningssession',
    uiRows: [{title:'Plan',text:'5-sessions behandlingsplan'},{title:'Påminding',text:'Sendes inden hvert besøg'}],
    uiButton: 'Book session',
    solutionBadge: 'Patientflow',
    solutionTitle: 'WayPAY understøtter sessioner, planer og påmindelser.',
    solutionText: 'Patienter ved, hvad de skal booke, og klinikker får en klarere kalender.',
    flowBadge: 'Fysio-flow',
    flowTitle: 'Fra første session til opfølgning',
    flow: [{title:'Vælg session',text:'Første gang, opfølgning eller vurdering — patienten vælger.'},{title:'Vælg tid',text:'Se ledige tider pr. terapeut.'},{title:'Bekræft forløb',text:'Sessionsplan synlig ved booking.'},{title:'Påminding',text:'Reminder inden hvert besøg i planen.'}],
    featuresBadge: 'Fysio-features',
    featuresTitle: 'Bygget til behandlingskontinuitet.',
    featuresText: 'Explaineren fokuserer på sessioner, pakker og patientpåmindelser.',
    features: [{icon:'fa-heartbeat',title:'Sessionstyper',text:'Første gang, opfølgning og plan.'},{icon:'fa-list-ol',title:'Behandlingsforløb',text:'Multi-sessioners planer med klar struktur.'},{icon:'fa-user-md',title:'Terapeutvalg',text:'Book med specifik behandler.'},{icon:'fa-bell',title:'Forløbspåmindelser',text:'Reminder inden hver session.'}],
    ctaTitle: 'Gør behandlingsplaner nemmere',
    ctaText: 'Hjælp patienter med at booke den rigtige session.',
    voiceovers: ['Fysioterapi kræver kontinuitet.','Behandlingsplaner er svære at styre manuelt.','WayPAY understøtter sessioner, pakker og påmindelser.','Flowet er session, plan, booking og opfølgning.','Dette er skræddersyet til fysioterapi.','Gør behandlingsplaner nemmere.'],
  },
  therapy: {
    headline: 'Privat og rolig sessionsbooking.',
    subline: 'Klienter booker samtaler, sessioner eller forløb med et klart og professionelt flow.',
    pills: ['Private sessioner','Klare vilkår','Online eller fysisk'],
    metrics: [{value:'100%',label:'privat'},{value:'↓50%',label:'administrationstid'},{value:'24/7',label:'booking åben'}],
    keyFacts: ['Klienter booker diskret og trygt','Aflysningsregler vises klart ved booking','Fortrolighed understøttes i hele flowet'],
    problemBadge: 'Terapi-problemet',
    problemTitle: 'Klienter kræver tillid, inden de booker.',
    problemText: 'Flowet skal føles roligt, privat og professionelt — ikke transaktionelt.',
    photoTitle: 'Privat konsultationsflow',
    photoText: 'En rolig premium visuel retning for private sessioner og professionel tillid.',
    uiKicker: 'WayPAY Terapi',
    uiTitle: 'Privat session',
    uiRows: [{title:'Session',text:'Online eller fysisk'},{title:'Regler',text:'Aflysningspolitik vises'}],
    uiButton: 'Bekræft session',
    solutionBadge: 'Klientflow',
    solutionTitle: 'WayPAY gør sessionsrejsen rolig og klar.',
    solutionText: 'Klienter vælger tid og modtager bekræftelse uden unødig friktion.',
    flowBadge: 'Terapi-flow',
    flowTitle: 'Fra tillid til bekræftet session',
    flow: [{title:'Vælg format',text:'Online eller fysisk — klienten beslutter.'},{title:'Vælg tid',text:'Ledige tider uden overeksponering.'},{title:'Gennemgå vilkår',text:'Aflysningspolitik vises klart.'},{title:'Bekræft',text:'Stille bekræftelse, ingen friktion.'}],
    featuresBadge: 'Terapi-features',
    featuresTitle: 'Bygget til private samtaler.',
    featuresText: 'Explaineren fokuserer på diskretion, klare vilkår og sessionsbooking.',
    features: [{icon:'fa-lock',title:'Privat flow',text:'Ingen unødvendige persondata vises.'},{icon:'fa-file-text',title:'Klare vilkår',text:'Aflysningspolitik ved booking.'},{icon:'fa-video-camera',title:'Online eller fysisk',text:'Klienten vælger format.'},{icon:'fa-calendar',title:'Rolig booking',text:'Klar, professionel oplevelse.'}],
    ctaTitle: 'Gør sessionsbooking trygt',
    ctaText: 'Skab en rolig og professionel klientoplevelse.',
    voiceovers: ['Terapibooking kræver tillid.','Klienter har brug for et roligt og privat flow.','WayPAY bekræfter sessioner uden friktion.','Flowet er session, tid, regler og bekræftelse.','Dette er skræddersyet til terapi.','Gør sessionsbooking trygt.'],
  },
  yoga: {
    headline: 'Sælg hold, klippekort og rolige rutiner.',
    subline: 'Deltagere vælger hold, pakke og betaling i en simpel bookingrejse.',
    pills: ['Klippekort','Små hold','Venteliste'],
    metrics: [{value:'10',label:'klip pr. kort'},{value:'↑45%',label:'fastholdelse'},{value:'0',label:'overfyldte hold'}],
    keyFacts: ['Holdkapacitet opdateres automatisk','Klippekort og pakker sælges i samme flow','Venteliste reducerer tomme pladser'],
    problemBadge: 'Studio-problemet',
    problemTitle: 'Små hold kræver klar kapacitetsstyring.',
    problemText: 'Yoga- og pilates-studier har brug for nem tilmelding, ventelistefunktion og klar betaling for klippekort.',
    photoTitle: 'Studie-holdrejse',
    photoText: 'En visuel retning fokuseret på rolige hold, kapacitet og gentaget fremmøde.',
    uiKicker: 'WayPAY Studie',
    uiTitle: 'Pilates · Tirsdag 18:00',
    uiRows: [{title:'Klippekort',text:'10-sessions pas'},{title:'Kapacitet',text:'2 pladser tilbage'}],
    uiButton: 'Book hold',
    solutionBadge: 'Deltagerflow',
    solutionTitle: 'WayPAY gør interesse til en bekræftet holdplads.',
    solutionText: 'Deltagere vælger hold og betalingstype uden at skrive først.',
    flowBadge: 'Studie-flow',
    flowTitle: 'Fra holdinteresse til fremmøde',
    flow: [{title:'Vælg hold',text:'Yoga, pilates eller reformer — deltageren vælger stil.'},{title:'Vælg klippekort',text:'Enkelt, 10 klip eller månedligt.'},{title:'Book plads',text:'Kapacitet vises — venteliste hvis fuldt.'},{title:'Påminding',text:'Sendes inden hvert hold.'}],
    featuresBadge: 'Studie-features',
    featuresTitle: 'Bygget til rolig studiodrift.',
    featuresText: 'Fokus på hold, pladser, kapacitet og påmindelser.',
    features: [{icon:'fa-leaf',title:'Holdtyper',text:'Yoga, pilates, reformer og mere.'},{icon:'fa-ticket',title:'Klippekort',text:'10 klip og månedlige muligheder.'},{icon:'fa-users',title:'Kapacitetsstyring',text:'Auto-venteliste når hold er fuldt.'},{icon:'fa-bell',title:'Holdpåmindelser',text:'Påminding reducerer udeblivelser.'}],
    ctaTitle: 'Fyld hold med mindre administration',
    ctaText: 'Gør holdbooking rolig og klar.',
    voiceovers: ['Yoga og pilates kræver rolig holdbooking.','Små hold kræver klar kapacitet.','WayPAY gør interesse til en bekræftet plads.','Flowet er hold, pas, betaling og fremmøde.','Dette er skræddersyet til studier.','Fyld hold med mindre administration.'],
  },
  consultant: {
    headline: 'Sælg tid uden kalenderkaos.',
    subline: 'Klienter vælger session, format og tid, mens betaling håndteres i samme flow.',
    pills: ['Tidspakker','Sessionsformater','Forudbetaling'],
    metrics: [{value:'↑80%',label:'betalt på forhånd'},{value:'0',label:'kalenderkaos'},{value:'3x',label:'pakkebookinger'}],
    keyFacts: ['Klienter booker sessionen, inden de mailer','Pakker og enkelt-sessioner sælges klart','Betaling sker ved booking — ingen faktura nødvendig'],
    problemBadge: 'Konsulent-problemet',
    problemTitle: 'Tid er produktet, men koordinering stjæler det.',
    problemText: 'Konsulenter mister fakturerbare timer, når booking, ombooking og betaling håndteres manuelt.',
    photoTitle: 'Professionel sessionsbooking',
    photoText: 'En mødefokuseret visuel rejse for konsulenter, coaches og rådgivere.',
    uiKicker: 'WayPAY Konsulent',
    uiTitle: 'Strategisession',
    uiRows: [{title:'Format',text:'Online eller fysisk'},{title:'Pakke',text:'Enkelt opkald eller 5-sessions plan'}],
    uiButton: 'Book session',
    solutionBadge: 'Klientflow',
    solutionTitle: 'Klienten vælger sessionen, inden den første mail.',
    solutionText: 'Booking, regler og betaling er klare fra starten.',
    flowBadge: 'Konsulent-flow',
    flowTitle: 'Fra forespørgsel til booket session',
    flow: [{title:'Vælg session',text:'Strategi, coaching eller rådgivning — klienten vælger.'},{title:'Vælg format',text:'Online eller fysisk.'},{title:'Vælg pakke',text:'Enkelt eller multi-sessioners plan.'},{title:'Betal og bekræft',text:'Betaling sikrer tidsblokken.'}],
    featuresBadge: 'Konsulent-features',
    featuresTitle: 'Bygget til at sælge ekspertise.',
    featuresText: 'Fokus på sessionstyper, pakker og kalenderklarhed.',
    features: [{icon:'fa-clock-o',title:'Tidspakker',text:'Enkelt og multi-sessioners planer.'},{icon:'fa-laptop',title:'Online eller fysisk',text:'Klienten vælger inden booking.'},{icon:'fa-credit-card',title:'Forudbetaling',text:'Reducerer planlægningsrisiko.'},{icon:'fa-calendar-check-o',title:'Kalenderklarhed',text:'Ingen frem-og-tilbage om tider.'}],
    ctaTitle: 'Sælg din tid klart',
    ctaText: 'Lad klienter booke den rette session.',
    voiceovers: ['Konsulenter sælger tid og ekspertise.','Koordinering må ikke stjæle fakturerbare timer.','WayPAY giver klienter et klart sessionsflow.','Flowet er session, format, tid og betaling.','Dette er skræddersyet til konsulenter.','Sælg din tid klart.'],
  },
  education: {
    headline: 'Sælg kurspladser og undervisning online.',
    subline: 'Deltagere vælger kursus, dato og betaling med klar kapacitet og bekræftelse.',
    pills: ['Kurspladser','Kapacitetsstyring','Tilmelding + betaling'],
    metrics: [{value:'12',label:'pladser pr. kursus'},{value:'0',label:'overbooking'},{value:'100%',label:'betalt ved tilmelding'}],
    keyFacts: ['Kapacitet opdateres automatisk ved tilmelding','Betaling ved tilmelding sikrer commitment','Deltagere modtager klar bekræftelse'],
    problemBadge: 'Kursus-problemet',
    problemTitle: 'Kurspladser skal være nemme at købe og svære at overbooke.',
    problemText: 'Manuel tilmelding gør kapacitet, betaling og deltagerinformation sværere at styre.',
    photoTitle: 'Kurstilmeldingsrejse',
    photoText: 'Et læringscentreret visuelt flow for kurser, lektioner og workshops.',
    uiKicker: 'WayPAY Kurser',
    uiTitle: 'Begynderkursus',
    uiRows: [{title:'Pladser',text:'8 af 12 tilgængelige'},{title:'Betaling',text:'Betalt ved tilmelding'}],
    uiButton: 'Reserver plads',
    solutionBadge: 'Deltagerflow',
    solutionTitle: 'Deltagere tilmelder sig og betaler i én klar rejse.',
    solutionText: 'Kapaciteten opdateres automatisk, og bekræftelser reducerer support.',
    flowBadge: 'Kursus-flow',
    flowTitle: 'Fra kursusvalg til bekræftet plads',
    flow: [{title:'Vælg kursus',text:'Begynder, videregående eller workshop.'},{title:'Se ledige pladser',text:'Pladser i realtid.'},{title:'Tilføj deltagerinfo',text:'Navn og detaljer indsamles på forhånd.'},{title:'Betal og bekræft',text:'Betaling = reserveret plads.'}],
    featuresBadge: 'Kursus-features',
    featuresTitle: 'Bygget til kapacitet og læringsrejser.',
    featuresText: 'Fokus på pladser, datoer, deltagerinfo og betaling.',
    features: [{icon:'fa-graduation-cap',title:'Kurskatalog',text:'Alle kurser med datoer og kapacitet.'},{icon:'fa-users',title:'Pladsstyring',text:'Auto-stop når kurset er fuldt.'},{icon:'fa-id-card-o',title:'Deltagerinfo',text:'Detaljer indsamles ved booking.'},{icon:'fa-credit-card',title:'Betalt tilmelding',text:'Betaling bekræfter reservationen.'}],
    ctaTitle: 'Gør kurstilmelding enkel',
    ctaText: 'Lad deltagere reservere og betale online.',
    voiceovers: ['Kurser kræver kapacitetsstyring.','Tilmelding og betaling bør hænge sammen.','WayPAY giver deltagere et klart kursusflow.','Flowet er kursus, plads, betaling og bekræftelse.','Dette er skræddersyet til undervisning.','Gør kurstilmelding enkel.'],
  },
  cleaning: {
    headline: 'Gør gentagne services til automatiske aftaler.',
    subline: 'Kunder vælger service, frekvens og betaling, så tilbagevendende arbejde kører automatisk.',
    pills: ['Tilbagevendende service','Frekvensvalg','Auto-betaling'],
    metrics: [{value:'↑90%',label:'på tilbagevendende planer'},{value:'0',label:'manuel fakturering'},{value:'2x',label:'kundens levetid'}],
    keyFacts: ['Serviceaftaler kører automatisk efter oprettelse','Kunder vælger frekvens og betalingsplan','Ingen manuel fakturering pr. besøg'],
    problemBadge: 'Service-problemet',
    problemTitle: 'Tilbagevendende arbejde bliver rodet uden struktur.',
    problemText: 'Rengøringsvirksomheder har brug for klare aftaler, planer og betaling for gentagne jobs.',
    photoTitle: 'Tilbagevendende serviceflow',
    photoText: 'En servicevirksomheds-rejse fokuseret på gentagne besøg og klare aftaler.',
    uiKicker: 'WayPAY Service',
    uiTitle: 'Hjemmerengøring',
    uiRows: [{title:'Frekvens',text:'Hver 2. uge'},{title:'Plan',text:'Tilbagevendende betaling'}],
    uiButton: 'Start aftale',
    solutionBadge: 'Serviceflow',
    solutionTitle: 'WayPAY gør gentagne jobs til enkle aftaler.',
    solutionText: 'Kunden vælger frekvens og betaling, mens virksomheden får en klarere plan.',
    flowBadge: 'Rengørings-flow',
    flowTitle: 'Fra én forespørgsel til tilbagevendende aftale',
    flow: [{title:'Vælg service',text:'Hjemmerengøring, kontor eller dybderengøring.'},{title:'Vælg frekvens',text:'Ugentlig, hver 2. uge eller månedlig.'},{title:'Start aftale',text:'Vilkår og betaling sættes én gang.'},{title:'Auto-kørsel',text:'Besøg bekræftes automatisk hver periode.'}],
    featuresBadge: 'Service-features',
    featuresTitle: 'Bygget til serviceaftaler.',
    featuresText: 'Fokus på frekvens, tilbagevendende betaling og klare kundevilkår.',
    features: [{icon:'fa-magic',title:'Servicetyper',text:'Hjem, kontor og dybderengøring.'},{icon:'fa-repeat',title:'Frekvens',text:'Ugentlig, hver 2. uge eller månedlig.'},{icon:'fa-credit-card',title:'Auto-betaling',text:'Ingen manuel fakturering pr. besøg.'},{icon:'fa-file-text-o',title:'Klar aftale',text:'Vilkår sat på forhånd, ingen overraskelser.'}],
    ctaTitle: 'Gør serviceaftaler nemmere',
    ctaText: 'Gør tilbagevendende arbejde til stabil omsætning.',
    voiceovers: ['Rengøringsvirksomheder har brug for tilbagevendende aftaler.','Manuel gentagelse bliver rodet.','WayPAY kobler service, frekvens og betaling.','Flowet er service, frekvens, betaling og plan.','Dette er skræddersyet til rengøring.','Gør serviceaftaler nemmere.'],
  },
  garden: {
    headline: 'Book sæsonservice og gentagne besøg.',
    subline: 'Kunder vælger haveopgave, besøgsvindue og valgfri tilbagevendende service.',
    pills: ['Sæsonopgaver','Besøgsvinduer','Tilbagevendende service'],
    metrics: [{value:'4',label:'sæsontoppe'},{value:'↑55%',label:'stamkunder'},{value:'0',label:'missede vinduer'}],
    keyFacts: ['Sæsonservice er nem at planlægge online','Kunder vælger opgave og besøgsvindue selv','Tilbagevendende aftaler kører automatisk'],
    problemBadge: 'Haveservice-problemet',
    problemTitle: 'Sæsonefterspørgsel kræver enkel planlægning.',
    problemText: 'Haveservice varierer efter opgave, sæson og frekvens, så kunder har brug for en klar måde at anmode på.',
    photoTitle: 'Sæsonservice booking',
    photoText: 'Et haveservice-flow fokuseret på sæsoner, opgaver og gentagne besøg.',
    uiKicker: 'WayPAY Have',
    uiTitle: 'Plæne- og hækkeklipning',
    uiRows: [{title:'Opgave',text:'Hækkeklipning'},{title:'Gentagelse',text:'Månedlig mulighed'}],
    uiButton: 'Book besøg',
    solutionBadge: 'Haveflow',
    solutionTitle: 'WayPAY gør udendørs service nem at anmode om.',
    solutionText: 'Kunden vælger opgave og besøgsvindue, mens virksomheden får en struktureret anmodning.',
    flowBadge: 'Have-flow',
    flowTitle: 'Fra haveopgave til planlagt besøg',
    flow: [{title:'Vælg opgave',text:'Plæne, hæk, blade eller oprydning.'},{title:'Vælg vindue',text:'Kunden sætter foretrukket besøgsvindue.'},{title:'Valgfri gentagelse',text:'Sæt tilbagevendende besøg for sæsonen.'},{title:'Bekræft',text:'Virksomheden får en struktureret anmodning.'}],
    featuresBadge: 'Have-features',
    featuresTitle: 'Bygget til sæsondrift.',
    featuresText: 'Fokus på opgavetype, besøgsvinduer og tilbagevendende service.',
    features: [{icon:'fa-tree',title:'Opgavetyper',text:'Plæne, hæk, blade og oprydning.'},{icon:'fa-calendar',title:'Besøgsvinduer',text:'Kunden vælger fleksible vinduer.'},{icon:'fa-repeat',title:'Sæsongentagelse',text:'Planlæg tilbagevendende sæsonservice.'},{icon:'fa-check-square-o',title:'Strukturerede anmodninger',text:'Slut med vage telefonopkald.'}],
    ctaTitle: 'Gør haveservice nemmere at booke',
    ctaText: 'Giv kunder en klar måde at anmode om arbejde.',
    voiceovers: ['Haveservice afhænger af sæsoner og opgaver.','Kunder har brug for en klar måde at anmode på.','WayPAY strukturerer opgave, besøg og betaling.','Flowet er opgave, tidsvindue, bekræftelse og service.','Dette er skræddersyet til haveservice.','Gør haveservice nemmere.'],
  },
  roof: {
    headline: 'Book inspektioner og servicebesøg med klarhed.',
    subline: 'Kunder anmoder om inspektion, vælger besøgsvindue og modtager klar bekræftelse.',
    pills: ['Inspektioner','Tilbudsopfølgning','Besøgsvinduer'],
    metrics: [{value:'↓60%',label:'telefonopkald'},{value:'1',label:'klar anmodning'},{value:'100%',label:'struktureret'}],
    keyFacts: ['Kunder anmoder om inspektion online','Besøgsvinduer vælges af kunden selv','Opfølgning og tilbud knyttes til forespørgslen'],
    problemBadge: 'Tagservice-problemet',
    problemTitle: 'Inspektionsanmodninger kræver struktur.',
    problemText: 'Tagservice starter ofte med et besøg, og uklare anmodninger skaber manuel frem-og-tilbage.',
    photoTitle: 'Inspektionsbesøg-rejse',
    photoText: 'Et field-service visuelt flow fokuseret på inspektion, tilbud og opfølgning.',
    uiKicker: 'WayPAY Tag',
    uiTitle: 'Taginspektion',
    uiRows: [{title:'Besøg',text:'Inspektionsvindue'},{title:'Opfølgning',text:'Tilbud efter besøg'}],
    uiButton: 'Book inspektion',
    solutionBadge: 'Serviceflow',
    solutionTitle: 'WayPAY gør inspektionsbooking klar.',
    solutionText: 'Kunder vælger et servicebesøg og ved, hvad der sker derefter.',
    flowBadge: 'Tag-flow',
    flowTitle: 'Fra problem til planlagt inspektion',
    flow: [{title:'Beskriv problem',text:'Kunden forklarer problemet på forhånd.'},{title:'Vælg besøgsvindue',text:'Fleksibelt tidsvindue for besøget.'},{title:'Bekræft anmodning',text:'Virksomheden får strukturerede oplysninger.'},{title:'Tilbudsopfølgning',text:'Tilbud sendt efter inspektionen.'}],
    featuresBadge: 'Tag-features',
    featuresTitle: 'Bygget til servicebesøg.',
    featuresText: 'Fokus på inspektion, besøgsvinduer og opfølgning.',
    features: [{icon:'fa-home',title:'Inspektionsanmodning',text:'Klart problem og vindue valgt.'},{icon:'fa-calendar',title:'Besøgsvinduer',text:'Fleksible ankomsttidsvinduer.'},{icon:'fa-file-text-o',title:'Tilbudsflow',text:'Tilbud sendt efter inspektion.'},{icon:'fa-check-circle',title:'Ingen gætteri',text:'Virksomheden ved, hvad der venter.'}],
    ctaTitle: 'Gør tagservice nemmere at anmode om',
    ctaText: 'Giv kunder en struktureret måde at booke inspektion.',
    voiceovers: ['Tagservice starter med inspektion.','Anmodninger kræver struktur.','WayPAY gør besøgsbooking klar.','Flowet er problem, besøg, bekræftelse og opfølgning.','Dette er skræddersyet til tagservice.','Gør inspektion nemmere at booke.'],
  },
  auto: {
    headline: 'Book servicebesøg uden telefonkaos.',
    subline: 'Kunder vælger servicetype, tidspunkt og modtager klar bekræftelse inden ankomst.',
    pills: ['Servicetyper','Afleveringsvinduer','Køretøjsdetaljer'],
    metrics: [{value:'↓70%',label:'telefonbooking'},{value:'100%',label:'info på forhånd'},{value:'24/7',label:'anmodning åben'}],
    keyFacts: ['Kunder angiver køretøjsdetaljer ved booking','Tidsvinduer for aflevering vises klart','Værkstedet får ordren klar inden ankomst'],
    problemBadge: 'Værksteds-problemet',
    problemTitle: 'Serviceanmodninger kræver de rette informationer fra starten.',
    problemText: 'Værksteder mister tid, når kunder ringer for grundlæggende booking og servicedetaljer.',
    photoTitle: 'Værkstedsbooking-rejse',
    photoText: 'Et værksteds-specifikt visuelt flow for servicetyper, tidspunkter og kundedetaljer.',
    uiKicker: 'WayPAY Værksted',
    uiTitle: 'Servicecheck',
    uiRows: [{title:'Køretøj',text:'Kunden tilføjer detaljer'},{title:'Tidspunkt',text:'Afleveringsvindue'}],
    uiButton: 'Book service',
    solutionBadge: 'Værksteds-flow',
    solutionTitle: 'WayPAY samler de rette bookingdetaljer inden besøget.',
    solutionText: 'Værkstedet får klarere planlægning, og kunden får et professionelt flow.',
    flowBadge: 'Værksteds-flow',
    flowTitle: 'Fra servicebehov til booket besøg',
    flow: [{title:'Vælg service',text:'Service, check, dæk eller reparationer.'},{title:'Tilføj køretøjsinfo',text:'Mærke, model og detaljer indsamles.'},{title:'Vælg aflevering',text:'Fleksibelt vindue — morgen eller eftermiddag.'},{title:'Bekræft',text:'Værkstedet får komplette bookingoplysninger.'}],
    featuresBadge: 'Værksteds-features',
    featuresTitle: 'Bygget til serviceaftaler.',
    featuresText: 'Fokus på servicetype, afleveringsvinduer og kundedetaljer.',
    features: [{icon:'fa-car',title:'Servicemenu',text:'Alle servicetyper kan vælges.'},{icon:'fa-info-circle',title:'Køretøjsdetaljer',text:'Indsamles inden besøget.'},{icon:'fa-clock-o',title:'Afleveringsvinduer',text:'Fleksible ankomsttider.'},{icon:'fa-check-square-o',title:'Komplette oplysninger',text:'Ingen opfølgningsopkald nødvendige.'}],
    ctaTitle: 'Gør værkstedsbooking klarere',
    ctaText: 'Reducer telefonopkald og manuel planlægning.',
    voiceovers: ['Værksteder har brug for servicedetaljer på forhånd.','Telefonbooking skaber afbrydelser.','WayPAY strukturerer servicebooking.','Flowet er service, køretøj, tid og bekræftelse.','Dette er skræddersyet til værksteder.','Gør værkstedsbooking klarere.'],
  },
  equipment: {
    headline: 'Styr udstyr, periode og returnering.',
    subline: 'Kunder lejer værktøj eller udstyr med klar tilgængelighed, betaling og returvilkår.',
    pills: ['Tilgængelighed','Depositum','Returvilkår'],
    metrics: [{value:'0',label:'dobbeltbookinger'},{value:'100%',label:'depositumsklarhed'},{value:'24/7',label:'reservationer åbne'}],
    keyFacts: ['Tilgængelighed vises i realtid','Depositum og returvilkår er klare ved booking','Sen returnering håndteres automatisk'],
    problemBadge: 'Udlejnings-problemet',
    problemTitle: 'Udstyrsleje kræver tilgængelighed og ansvar.',
    problemText: 'Manuel udlejning skaber risiko for dobbeltbooking, sen returnering og skadeshåndtering.',
    photoTitle: 'Udstyrsleje-flow',
    photoText: 'En udlejnings-specifik rejse for tilgængelighed, ansvar og returnering.',
    uiKicker: 'WayPAY Udstyr',
    uiTitle: 'Maskinudlejning',
    uiRows: [{title:'Periode',text:'Weekend-udlejning'},{title:'Returnering',text:'Mandag 09:00'}],
    uiButton: 'Reserver udstyr',
    solutionBadge: 'Udlejnings-flow',
    solutionTitle: 'WayPAY gør udstyrsleje mere forudsigelig.',
    solutionText: 'Kunder forstår, hvad de lejer, hvornår det returneres, og hvad de betaler.',
    flowBadge: 'Udstyrsleje-flow',
    flowTitle: 'Fra reservation til returneret udstyr',
    flow: [{title:'Vælg udstyr',text:'Kun tilgængeligt udstyr vises.'},{title:'Vælg periode',text:'Timer, dage eller weekend-leje.'},{title:'Betal depositum',text:'Depositum indsamles på forhånd.'},{title:'Returbekræftelse',text:'Returdato og vilkår er klare.'}],
    featuresBadge: 'Udstyrsleje-features',
    featuresTitle: 'Bygget til lejekontrol.',
    featuresText: 'Fokus på tilgængelighed, depositum, forsinkelsesgebyr og returnering.',
    features: [{icon:'fa-wrench',title:'Udstyrstilgængelighed',text:'Lager i realtid vises.'},{icon:'fa-lock',title:'Depositum',text:'Betalt på forhånd, klare vilkår.'},{icon:'fa-calendar',title:'Lejeperiode',text:'Timer, dage eller pakker.'},{icon:'fa-undo',title:'Returflow',text:'Returdato og forsinkelsesgebyr forklaret.'}],
    ctaTitle: 'Gør udstyrsleje nemmere',
    ctaText: 'Giv kunder en klar lejeoplevelse.',
    voiceovers: ['Udstyrsleje kræver kontrol.','Manuel udlejning skaber risiko.','WayPAY strukturerer periode, betaling og returnering.','Flowet er udstyr, periode, betaling og returnering.','Dette er skræddersyet til udstyrsleje.','Gør udstyrsleje nemmere.'],
  },
  pet: {
    headline: 'Book dyrepasservice med tillid og klarhed.',
    subline: 'Kunder booker pasningsservices, gentagne besøg og aftaler med klar betaling.',
    pills: ['Pasningstyper','Gentagne besøg','Tillid-først flow'],
    metrics: [{value:'↑70%',label:'stamkunder'},{value:'100%',label:'vilkår vises'},{value:'24/7',label:'booking åben'}],
    keyFacts: ['Kunder ser servicedetaljer klart inden booking','Gentagne besøg kan planlægges automatisk','Påmindelser sikrer stabilt fremmøde'],
    problemBadge: 'Dyrepasser-problemet',
    problemTitle: 'Dyrepasservice afhænger af tillid og klare forventninger.',
    problemText: 'Kunder har brug for at forstå service, tid, vilkår og gentagelsesmuligheder inden booking.',
    photoTitle: 'Dyrepasser kundeoplevelse',
    photoText: 'Et varmt visuelt flow fokuseret på tillid, omsorg, gentagne besøg og kommunikation.',
    uiKicker: 'WayPAY Dyrepasser',
    uiTitle: 'Dyrepasserbesøg',
    uiRows: [{title:'Service',text:'Gåtur eller pasningsbesøg'},{title:'Gentagelse',text:'Ugentlig mulighed'}],
    uiButton: 'Book pasning',
    solutionBadge: 'Pasningsflow',
    solutionTitle: 'WayPAY gør dyrepasservice nemmere at stole på.',
    solutionText: 'Kunden ser servicedetaljer og bekræfter uden forvirring.',
    flowBadge: 'Dyrepasser-flow',
    flowTitle: 'Fra pasningsbehov til bekræftet besøg',
    flow: [{title:'Vælg pasningstype',text:'Gåtur, dagpasning eller hjemmebesøg.'},{title:'Vælg tid',text:'Kunden vælger foretrukket tidspunkt.'},{title:'Valgfri gentagelse',text:'Ugentlig eller hver 2. uge.'},{title:'Bekræft',text:'Påmindelser holder begge parter klar.'}],
    featuresBadge: 'Dyrepasser-features',
    featuresTitle: 'Bygget til tillidsbaserede services.',
    featuresText: 'Fokus på servicedetaljer, gentagne besøg og påmindelser.',
    features: [{icon:'fa-paw',title:'Pasningstyper',text:'Gåtur, dagpasning og hjemmebesøg.'},{icon:'fa-heart',title:'Tillidselementer',text:'Passerinfo og vilkår vises på forhånd.'},{icon:'fa-repeat',title:'Tilbagevendende',text:'Ugentlig eller hver 2. uge.'},{icon:'fa-bell',title:'Påmindelser',text:'Begge parter minder om hvert besøg.'}],
    ctaTitle: 'Gør dyrepasservice nem at booke',
    ctaText: 'Giv kunder et klart og omsorgsfuldt flow.',
    voiceovers: ['Dyrepasservice afhænger af tillid.','Kunder har brug for klarhed inden booking.','WayPAY strukturerer service, gentagelse og betaling.','Flowet er pasningstype, tid, bekræftelse og påminding.','Dette er skræddersyet til dyrepasservice.','Gør dyrepasservice nem at booke.'],
  },
  photography: {
    headline: 'Sælg fotosessioner med depositum og klarhed.',
    subline: 'Kunder vælger sessionstype, dato, pakke og depositum i ét premium bookingflow.',
    pills: ['Sessionspakker','Depositum','Leveringsinfo'],
    metrics: [{value:'100%',label:'depositum sikret'},{value:'↑50%',label:'forespørgsel til booking'},{value:'0',label:'uklare forventninger'}],
    keyFacts: ['Depositum sikrer commitment inden shoot','Pakker og tilvalg sælges klart i flowet','Kundens forventninger afklares inden dagen'],
    problemBadge: 'Foto-problemet',
    problemTitle: 'Fotosessioner kræver commitment inden selve dagen.',
    problemText: 'Fotografer har brug for at sikre tid, forventninger og depositum inden sessionsdagen.',
    photoTitle: 'Fotosessions-booking',
    photoText: 'En visuel rejse for sessioner, depositum, pakker og kundernes forventninger.',
    uiKicker: 'WayPAY Fotografi',
    uiTitle: 'Portrætsession',
    uiRows: [{title:'Pakke',text:'Studiesession + redigering'},{title:'Depositum',text:'Betales ved booking'}],
    uiButton: 'Book shoot',
    solutionBadge: 'Klientflow',
    solutionTitle: 'WayPAY gør sessionen professionelt booket.',
    solutionText: 'Klienter vælger pakke, tid og depositum i ét flow.',
    flowBadge: 'Foto-flow',
    flowTitle: 'Fra forespørgsel til booket shoot',
    flow: [{title:'Vælg session',text:'Portræt, familie, produkt eller event.'},{title:'Vælg pakke',text:'Pakke inkluderer redigering og leveringsinfo.'},{title:'Betal depositum',text:'Depositum bekræfter shoot-datoen.'},{title:'Bekræft detaljer',text:'Klientens forventninger sat inden dagen.'}],
    featuresBadge: 'Fotografi-features',
    featuresTitle: 'Bygget til kreative sessioner.',
    featuresText: 'Fokus på pakker, depositum, datoer og bekræftelse.',
    features: [{icon:'fa-camera',title:'Sessionstyper',text:'Portræt, familie, produkt og event.'},{icon:'fa-gift',title:'Pakker',text:'Inkluderer redigering og leveringsinfo.'},{icon:'fa-credit-card',title:'Depositum',text:'Betalt ved booking — dato sikret.'},{icon:'fa-file-text-o',title:'Forventninger',text:'Klienten ved, hvad der sker.'}],
    ctaTitle: 'Book fotosessioner med tryghed',
    ctaText: 'Gør forespørgsler til betalte sessioner.',
    voiceovers: ['Fotografi kræver commitment.','Depositum sikrer sessionen.','WayPAY strukturerer pakke, tid og betaling.','Flowet er session, pakke, dato og depositum.','Dette er skræddersyet til fotografer.','Book sessioner med tryghed.'],
  },
  onlineBooking: {
    headline: 'Online booking forklaret i ét visuelt flow.',
    subline: 'Kunder vælger service, tid og bekræftelse uden at skrive først.',
    pills: ['Live tilgængelighed','Selvbetjening','Øjeblikkelig bekræftelse'],
    metrics: [{value:'↓80%',label:'administrationstid'},{value:'24/7',label:'booking åben'},{value:'↑40%',label:'konvertering'}],
    keyFacts: ['Kunder ser ledige tider uden at ringe','Booking bekræftes automatisk','Virksomheden modtager ordren klar til handling'],
    problemBadge: 'Booking-problemet',
    problemTitle: 'Kunder ønsker ikke at spørge om ledige tider.',
    problemText: 'Online booking fjerner friktion ved at vise tilgængelige muligheder direkte.',
    photoTitle: 'Booking uden frem-og-tilbage',
    photoText: 'En produktfokuseret visual for servicevalg, tilgængelighed og bekræftelse.',
    uiKicker: 'WayPAY Booking',
    uiTitle: 'Vælg service og tid',
    uiRows: [{title:'Service',text:'Valgt af kunden'},{title:'Tid',text:'Kun ledige tider'}],
    uiButton: 'Bekræft booking',
    solutionBadge: 'Bookingflow',
    solutionTitle: 'WayPAY gør tilgængelighed til handling.',
    solutionText: 'Kunder bevæger sig fra interesse til bekræftet booking i få trin.',
    flowBadge: 'Online bookingflow',
    flowTitle: 'Fra besøgende til booking',
    flow: [{title:'Åbn bookingside',text:'Servicetyper og tilgængelighed vises.'},{title:'Vælg service',text:'Kunden vælger det, de har brug for.'},{title:'Vælg tid',text:'Kun ledige tider vises.'},{title:'Bekræft',text:'Begge parter modtager øjeblikkelig bekræftelse.'}],
    featuresBadge: 'Feature-detaljer',
    featuresTitle: 'Bygget til at reducere bookingfriktion.',
    featuresText: 'Fokus på tilgængelighed, servicevalg og bekræftelse.',
    features: [{icon:'fa-calendar-check-o',title:'Live tilgængelighed',text:'Tidsleder opdateres automatisk.'},{icon:'fa-mouse-pointer',title:'Selvbetjening',text:'Ingen beskeder nødvendige for at booke.'},{icon:'fa-envelope-o',title:'Øjeblikkelig bekræftelse',text:'Sendt umiddelbart efter booking.'},{icon:'fa-mobile',title:'Virker på mobil',text:'Optimeret til alle enheder.'}],
    ctaTitle: 'Gør booking til selvbetjening',
    ctaText: 'Lad kunder booke, når de er klar.',
    voiceovers: ['Online booking fjerner frem-og-tilbage.','Kunder vil se ledige tider.','WayPAY gør tilgængelighed til handling.','Flowet er service, tid, bekræftelse og opdatering.','Denne feature er central for WayPAY.','Gør booking til selvbetjening.'],
  },
  prepayment: {
    headline: 'Forudbetaling gør bookinger mere forpligtende.',
    subline: 'Kunder betaler ved booking, så aftalen føles klar fra begyndelsen.',
    pills: ['Forudbetaling','Færre no-shows','Øjeblikkelig kvittering'],
    metrics: [{value:'↓45%',label:'no-shows'},{value:'↑30%',label:'cashflow'},{value:'100%',label:'kvittering auto-sendt'}],
    keyFacts: ['En betalt booking er sværere at glemme','Forudbetaling forbedrer cashflow fra dag ét','Kvittering sendes automatisk ved booking'],
    problemBadge: 'Betalings-problemet',
    problemTitle: 'En booking uden betaling er nemmere at ignorere.',
    problemText: 'Forudbetaling eller depositum skaber klarere forpligtelse og forbedrer cashflow.',
    photoTitle: 'Betaling koblet til booking',
    photoText: 'En feature-visual fokuseret på forpligtelse, betaling og cashflow.',
    uiKicker: 'WayPAY Betaling',
    uiTitle: 'Betal ved booking',
    uiRows: [{title:'Beløb',text:'Vises inden bekræftelse'},{title:'Kvittering',text:'Sendes automatisk'}],
    uiButton: 'Betal og bekræft',
    solutionBadge: 'Betalingsflow',
    solutionTitle: 'WayPAY kobler booking og betaling.',
    solutionText: 'Kunden bekræfter aftalen med betaling i samme rejse.',
    flowBadge: 'Forudbetalingsflow',
    flowTitle: 'Fra intention til betalt bekræftelse',
    flow: [{title:'Vælg service',text:'Beløb vises klart inden betaling.'},{title:'Betal ved booking',text:'Kortbetaling eller faktura på forhånd.'},{title:'Modtag kvittering',text:'Sendt automatisk efter betaling.'},{title:'Bekræftet',text:'Virksomheden ved, at bookingen er seriøs.'}],
    featuresBadge: 'Betalings-features',
    featuresTitle: 'Bygget til forpligtelse.',
    featuresText: 'Fokus på betaling, kvittering og reduktion af no-shows.',
    features: [{icon:'fa-credit-card',title:'Betaling ved booking',text:'Kunden betaler inden ankomst.'},{icon:'fa-envelope-o',title:'Auto-kvittering',text:'Sendt øjeblikkeligt til kunden.'},{icon:'fa-user-times',title:'Færre no-shows',text:'Betalte bookinger aflyses sjældnere.'},{icon:'fa-line-chart',title:'Bedre cashflow',text:'Omsætning bekræftet inden besøget.'}],
    ctaTitle: 'Gør bookinger mere forpligtende',
    ctaText: 'Kobl betaling til bookingøjeblikket.',
    voiceovers: ['Forudbetaling øger forpligtelsen.','En gratis booking er nemmere at ignorere.','WayPAY kobler booking og betaling.','Flowet er beløb, betaling, kvittering og bekræftelse.','Denne feature forbedrer cashflow.','Gør bookinger mere forpligtende.'],
  },
  reminders: {
    headline: 'Automatiske påmindelser reducerer manuel opfølgning.',
    subline: 'Kunder modtager klare bekræftelser og påmindelser inden aftalen eller udlejningen.',
    pills: ['Bookingbekræftelse','Forudgående påminding','Auto-send'],
    metrics: [{value:'↓35%',label:'no-shows'},{value:'0',label:'manuelle påmindelser'},{value:'2',label:'beskeder pr. booking'}],
    keyFacts: ['Bekræftelse sendes automatisk ved booking','Påminding sendes inden hvert besøg','Kunder husker bedre — færre supportbeskeder'],
    problemBadge: 'Påmindings-problemet',
    problemTitle: 'Folk glemmer selv vigtige aftaler.',
    problemText: 'Manuel påminding er tidskrævende, og inkonsekvent kommunikation skaber forvirring.',
    photoTitle: 'Påmindelseskommunikation',
    photoText: 'En feature-visual fokuseret på timing, klarhed og færre supportbeskeder.',
    uiKicker: 'WayPAY Påmindelser',
    uiTitle: 'Påmindelsesplan',
    uiRows: [{title:'Bekræftelse',text:'Sendes efter booking'},{title:'Påminding',text:'Sendes inden besøg'}],
    uiButton: 'Aktiver påmindelser',
    solutionBadge: 'Beskedflow',
    solutionTitle: 'WayPAY holder kunden informeret automatisk.',
    solutionText: 'Klare beskeder hjælper kunder med at huske og reducerer support.',
    flowBadge: 'Påmindelsesflow',
    flowTitle: 'Fra booking til husket aftale',
    flow: [{title:'Booking bekræftet',text:'Bekræftelse sendt øjeblikkeligt.'},{title:'Første påminding',text:'Sendt et par dage inden besøget.'},{title:'Dag-påminding',text:'Endelig påminding på selve dagen.'},{title:'Intet manuelt',text:'Alle beskeder sendes automatisk.'}],
    featuresBadge: 'Påmindings-features',
    featuresTitle: 'Bygget til færre glemte besøg.',
    featuresText: 'Fokus på bekræftelse, påmindelsestiming og kundekommunikation.',
    features: [{icon:'fa-check-circle',title:'Bookingbekræftelse',text:'Sendt øjeblikkeligt efter booking.'},{icon:'fa-bell',title:'Forudgående påminding',text:'Dage inden aftalen.'},{icon:'fa-clock-o',title:'Dag-påminding',text:'Sendt om morgenen på besøgsdagen.'},{icon:'fa-toggle-on',title:'Auto-send',text:'Intet manuelt arbejde kræves.'}],
    ctaTitle: 'Reducer manuelle påmindelser',
    ctaText: 'Lad beskeder køre automatisk.',
    voiceovers: ['Påmindelser reducerer manuel opfølgning.','Folk glemmer aftaler.','WayPAY holder kunden informeret.','Flowet er bekræftelse, påminding og fremmøde.','Denne feature understøtter alle brancher.','Reducer manuelle påmindelser.'],
  },
  bookingWebsite: {
    headline: 'En bookinghjemmeside forklarer, inden den konverterer.',
    subline: 'Kunder forstår servicen, stoler på tilbuddet og booker fra samme side.',
    pills: ['Serviceforklaring','Tillidsopbygning','Direkte booking CTA'],
    metrics: [{value:'↑55%',label:'konverteringsrate'},{value:'↓60%',label:'bounce rate'},{value:'1',label:'side til booking'}],
    keyFacts: ['Siden forklarer serviceværdien inden booking','CTA og booking er på samme side','SEO og AEO-struktur er indbygget'],
    problemBadge: 'Hjemmeside-problemet',
    problemTitle: 'Et bookinglink alene forklarer ikke værdien.',
    problemText: 'Kunder har ofte brug for kontekst, inden de vælger en service eller betaler.',
    photoTitle: 'Hjemmeside plus bookingflow',
    photoText: 'En produktvisual for landingsside, tillid, CTA og konvertering.',
    uiKicker: 'WayPAY Hjemmeside',
    uiTitle: 'Service-landingsside',
    uiRows: [{title:'Forklaring',text:'Hvad kunden får'},{title:'CTA',text:'Book direkte'}],
    uiButton: 'Åbn booking',
    solutionBadge: 'Hjemmeside-flow',
    solutionTitle: 'WayPAY kombinerer forklaring og handling.',
    solutionText: 'Siden besvarer spørgsmål og leder kunden til booking.',
    flowBadge: 'Hjemmeside-flow',
    flowTitle: 'Fra besøgende til booket kunde',
    flow: [{title:'Kunden ankommer',text:'Service forklaret klart på siden.'},{title:'Tillid opbygges',text:'Social bevis, billeder og vilkår.'},{title:'CTA vises',text:'Klar bookingknap over foldet.'},{title:'Booket',text:'Fra side til bekræftet booking.'}],
    featuresBadge: 'Hjemmeside-features',
    featuresTitle: 'Bygget til konvertering.',
    featuresText: 'Fokus på SEO, CTA, serviceforklaring og booking.',
    features: [{icon:'fa-globe',title:'Serviceside',text:'Forklar, hvad kunder får.'},{icon:'fa-star',title:'Tillidselementer',text:'Anmeldelser, billeder og legitimitet.'},{icon:'fa-hand-pointer-o',title:'Booking CTA',text:'Direkte link til bookingflow.'},{icon:'fa-search',title:'SEO-klar',text:'Optimeret til AI og søgning.'}],
    ctaTitle: 'Gør besøgende til bookinger',
    ctaText: 'Brug en side, der forklarer og konverterer.',
    voiceovers: ['En bookinghjemmeside forklarer, inden den konverterer.','Et link alene er muligvis ikke nok.','WayPAY kombinerer forklaring og handling.','Flowet er besøgende, tillid, CTA og booking.','Denne feature understøtter SEO og konvertering.','Gør besøgende til bookinger.'],
  },
  rentalDeposit: {
    headline: 'Depositum gør udlejning sikrere og klarere.',
    subline: 'Kunder forstår depositum, lejeregler og returforventninger inden afhentning.',
    pills: ['Depositum på forhånd','Klare returvilkår','Auto-gebyrhåndtering'],
    metrics: [{value:'↓80%',label:'tvister'},{value:'100%',label:'vilkår klare ved booking'},{value:'0',label:'depositumsjagt'}],
    keyFacts: ['Depositum og returvilkår vises inden booking','Kunden accepterer vilkårene online','Skadesgebyr og returnering er klart defineret'],
    problemBadge: 'Depositums-problemet',
    problemTitle: 'Udlejning kræver sikkerhed, inden udstyret forlader stedet.',
    problemText: 'Depositum og vilkår reducerer usikkerhed om skader, sen returnering og ansvar.',
    photoTitle: 'Depositum og returtilbagesikring',
    photoText: 'En lejefunktions-visual for risiko, returnering og kundeansvar.',
    uiKicker: 'WayPAY Depositum',
    uiTitle: 'Lejedepositum',
    uiRows: [{title:'Depositum',text:'Vises inden booking'},{title:'Returnering',text:'Vilkår er klare'}],
    uiButton: 'Acceptér og reserver',
    solutionBadge: 'Depositumsflow',
    solutionTitle: 'WayPAY gør lejeansvar synligt.',
    solutionText: 'Kunder ser reglerne og bekræfter, inden lejemålet begynder.',
    flowBadge: 'Depositumsflow',
    flowTitle: 'Fra reservation til sikker returnering',
    flow: [{title:'Se depositumsbeløb',text:'Vises inden kunden reserverer.'},{title:'Forstå vilkår',text:'Returdato, skader og forsinkelsesgebyr forklaret.'},{title:'Betal depositum',text:'Indsamles ved reservation.'},{title:'Retur bekræftet',text:'Depositum frigives ved retur.'}],
    featuresBadge: 'Depositums-features',
    featuresTitle: 'Bygget til lejebeskyttelse.',
    featuresText: 'Fokus på depositum, vilkår, returnering og gebyrer.',
    features: [{icon:'fa-lock',title:'Depositumsklarhed',text:'Beløb vist inden reservation.'},{icon:'fa-file-text-o',title:'Returvilkår',text:'Klare regler for skader og forsinkelse.'},{icon:'fa-credit-card',title:'Indsamlet ved booking',text:'Ingen jagt efter returnering.'},{icon:'fa-check-circle',title:'Auto-frigivelse',text:'Depositum returneres automatisk.'}],
    ctaTitle: 'Gør udlejning sikrere',
    ctaText: 'Vis depositum og returregler klart.',
    voiceovers: ['Depositum gør udlejning sikrere.','Udlejning kræver sikkerhed inden afhentning.','WayPAY gør ansvar synligt.','Flowet er depositum, vilkår, leje og returnering.','Denne feature beskytter udlejningsvirksomheder.','Gør udlejning sikrere.'],
  },
  subscriptions: {
    headline: 'Tilbagevendende betalinger uden manuel opfølgning.',
    subline: 'Kunder vælger en plan, og betalinger fortsætter automatisk ifølge aftalen.',
    pills: ['Planvalg','Auto-betaling','Kundeportal'],
    metrics: [{value:'↑90%',label:'betalingssucces'},{value:'0',label:'manuel fakturering'},{value:'3x',label:'LTV vs. enkeltbookinger'}],
    keyFacts: ['Kunden vælger plan — betaling kører automatisk','Fejlede betalinger håndteres automatisk','Kundeportal giver selvbetjening'],
    problemBadge: 'Abonnements-problemet',
    problemTitle: 'Tilbagevendende omsætning kræver pålidelig gentagende betaling.',
    problemText: 'Manuel fakturering og opfølgning skaber friktion for både kunde og virksomhed.',
    photoTitle: 'Abonnementsplan-flow',
    photoText: 'En feature-visual for medlemskaber, planer og tilbagevendende omsætning.',
    uiKicker: 'WayPAY Abonnementer',
    uiTitle: 'Månedlig plan',
    uiRows: [{title:'Plan',text:'Valgt af kunden'},{title:'Betaling',text:'Kører automatisk'}],
    uiButton: 'Start plan',
    solutionBadge: 'Abonnementsflow',
    solutionTitle: 'WayPAY gør planer til automatisk betaling.',
    solutionText: 'Kunden vælger en plan, og virksomheden modtager forudsigelig tilbagevendende omsætning.',
    flowBadge: 'Abonnementsflow',
    flowTitle: 'Fra planvalg til tilbagevendende omsætning',
    flow: [{title:'Vælg plan',text:'Månedlig, kvartalsvis eller årlig mulighed.'},{title:'Sæt betaling',text:'Kort gemt én gang, kører automatisk.'},{title:'Adgang starter',text:'Kunden får øjeblikkelig adgang.'},{title:'Fornyes automatisk',text:'Ingen manuel fornyelse nødvendig.'}],
    featuresBadge: 'Abonnements-features',
    featuresTitle: 'Bygget til medlemskaber og planer.',
    featuresText: 'Fokus på planer, fornyelser, fejlede betalinger og kundeportal.',
    features: [{icon:'fa-list-alt',title:'Planmuligheder',text:'Månedlig, kvartalsvis og årlig.'},{icon:'fa-credit-card',title:'Auto-betaling',text:'Kører uden manuel fakturering.'},{icon:'fa-user-circle-o',title:'Kundeportal',text:'Kunden styrer sin plan.'},{icon:'fa-refresh',title:'Auto-fornyelse',text:'Abonnementer fortsætter automatisk.'}],
    ctaTitle: 'Gør abonnementer nemmere',
    ctaText: 'Gør gentagen værdi til gentagen betaling.',
    voiceovers: ['Abonnementer kræver pålidelig gentagende betaling.','Manuel opfølgning skaber friktion.','WayPAY gør planer til automatisk betaling.','Flowet er plan, betaling, fornyelse og portal.','Denne feature understøtter medlemskaber.','Gør abonnementer nemmere.'],
  },
};
